# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aMatrixSparseRevLex <- function(bS, M) {
    .Call('_MCARtest_aMatrixSparseRevLex', PACKAGE = 'MCARtest', bS, M)
}

infoS <- function(bS, M) {
    .Call('_MCARtest_infoS', PACKAGE = 'MCARtest', bS, M)
}

infoS2 <- function(bS, M) {
    .Call('_MCARtest_infoS2', PACKAGE = 'MCARtest', bS, M)
}

colVector <- function(cardS, cardChi) {
    .Call('_MCARtest_colVector', PACKAGE = 'MCARtest', cardS, cardChi)
}

margProj <- function(p, bS, M) {
    .Call('_MCARtest_margProj', PACKAGE = 'MCARtest', p, bS, M)
}

